import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { downloadTrainingFeedback, getTrainingFeedback } from "../services/platformService";

export default function TrainingFeedback() {
  const [rows, setRows] = useState([]); const [error, setError] = useState("");
  useEffect(() => { getTrainingFeedback().then(response => setRows(response.data)).catch(request => setError(request.response?.data?.detail || "Feedback unavailable.")); }, []);
  const download = async () => { const { data } = await downloadTrainingFeedback(); const url = URL.createObjectURL(data); const link = document.createElement("a"); link.href = url; link.download = "training-feedback.csv"; link.click(); URL.revokeObjectURL(url); };
  return <main className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-black uppercase tracking-wider text-emerald-700">Human-in-the-loop dataset</p><h1 className="text-3xl font-black">Training Feedback</h1></div><div className="flex gap-2"><button onClick={download} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Export CSV</button><Link to="/dashboard" className="rounded-xl bg-slate-900 px-4 py-2 font-bold text-white">Dashboard</Link></div></div>{error && <p className="mt-5 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>}<div className="mt-6 overflow-x-auto rounded-3xl bg-white shadow ring-1 ring-slate-200"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="p-4">Analysis</th><th className="p-4">AI</th><th className="p-4">Human decision</th><th className="p-4">Status</th><th className="p-4">Reason</th><th className="p-4">Reviewed</th></tr></thead><tbody>{rows.map(row => <tr key={row.analysis_id} className="border-t"><td className="p-4 font-black">{row.analysis_id}</td><td className="p-4">{row.ai_destination} ({((row.ai_confidence || 0) * 100).toFixed(1)}%)</td><td className="p-4 font-bold">{row.final_destination}</td><td className="p-4">{row.review_status}</td><td className="p-4">{row.review_reason}</td><td className="p-4">{row.reviewed_at ? new Date(row.reviewed_at).toLocaleString() : "—"}</td></tr>)}{!rows.length && !error && <tr><td colSpan="6" className="p-10 text-center text-slate-500">No reviewed predictions yet.</td></tr>}</tbody></table></div></div></main>;
}
