"""
Environmental Report Model — Milestone 4 (Environmental Impact Assessment Engine)

Stores environmental assessment report metadata for each analysed inventory item.
Numerical KPIs (CO₂, water, landfill, resource recovery) are NOT duplicated here —
they are always read live from the sustainability_metrics table.

Table: environmental_reports

One inventory item has AT MOST one environmental report row.
Re-running the assessment engine overwrites the existing row.
"""

from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class EnvironmentalReport(Base):
    """
    Persists environmental assessment metadata for a single inventory item.

    The report stores derived analytical artefacts (rating, summary, insights)
    while delegating all raw KPI values to ``sustainability_metrics``.

    Relationships
    -------------
    inventory : Inventory
        The parent inventory record this report belongs to.
    """

    __tablename__ = "environmental_reports"

    # ── Primary Key ───────────────────────────────────────────────────────────
    id = Column(Integer, primary_key=True, index=True)

    # ── Foreign Key ───────────────────────────────────────────────────────────
    inventory_id = Column(
        Integer,
        ForeignKey("inventory.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,   # one report per inventory item (upsert pattern)
        index=True,
    )

    # ── Derived Analytical Artefacts ──────────────────────────────────────────
    environmental_rating = Column(
        String,
        nullable=False,
    )
    """
    Performance band derived from sustainability_score.
    'Excellent' | 'Very Good' | 'Good' | 'Fair' | 'Needs Improvement'
    """

    summary = Column(Text, nullable=False)
    """
    Human-readable one-paragraph summary of the environmental assessment.
    Generated by the service layer from the KPI values.
    """

    generated_insights = Column(Text, nullable=False)
    """
    JSON-encoded list of 3–5 actionable environmental insight strings.
    Stored as Text so no JSON column type dependency is needed.
    Deserialised by the service/schema layer before serving to clients.
    """

    # ── Audit ──────────────────────────────────────────────────────────────────
    report_generated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── ORM Relationship ───────────────────────────────────────────────────────
    inventory = relationship(
        "Inventory",
        back_populates="environmental_report",
    )
