"""
Recycling Recommendation Model — Milestone 4

Stores individual recycling recommendations generated by the
Recommendation Engine for every analysed inventory item.

Table: recycling_recommendations

One inventory item may have MULTIPLE recommendation rows — one per
recommendation type generated (e.g. Donation + Fiber Recycling).
"""

from sqlalchemy import Column, Integer, String, Float, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class RecyclingRecommendation(Base):
    """
    Persists a single recycling recommendation entry for an inventory item.

    Relationships
    -------------
    inventory : Inventory
        The parent inventory record this recommendation belongs to.
    """

    __tablename__ = "recycling_recommendations"

    # ── Primary Key ───────────────────────────────────────────────────────────
    id = Column(Integer, primary_key=True, index=True)

    # ── Foreign Key ───────────────────────────────────────────────────────────
    inventory_id = Column(
        Integer,
        ForeignKey("inventory.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Classification Snapshot (captured at generation time) ─────────────────
    material_type = Column(String, nullable=False)    # e.g. "Cotton"
    waste_category = Column(String, nullable=False)  # e.g. "Recyclable"
    condition = Column(String, nullable=True)         # "Excellent" / "Good" / "Fair" / "Poor" / None

    # ── Recommendation Fields ─────────────────────────────────────────────────
    recommendation = Column(String, nullable=False)
    """
    Recommendation type name.
    Examples: "Fiber Recycling", "Mechanical Recycling", "Chemical Recycling",
              "Fabric Reuse", "Upcycling", "Donation", "Industrial Recovery"
    """

    description = Column(Text, nullable=False)
    """Short description of the recommended action."""

    reason = Column(Text, nullable=False)
    """Why this recommendation was chosen for this material + category."""

    environmental_benefit = Column(Text, nullable=False)
    """Expected environmental impact of following this recommendation."""

    priority = Column(String, nullable=False, default="Medium")
    """Execution priority: "High" | "Medium" | "Low" """

    # ── Audit ─────────────────────────────────────────────────────────────────
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # ── ORM Relationship ───────────────────────────────────────────────────────
    inventory = relationship(
        "Inventory",
        back_populates="recycling_recommendations",
    )
