from io import BytesIO
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
)

from .helpers import (
    report_header,
    report_footer,
    gap,
)

from .styles import (
    PAGE_MARGIN,
)

from .constants import (
    PLATFORM_NAME,
)


class BaseReport:
    """
    =========================================================

        Textile Waste Intelligence Platform

            Enterprise Report Base Class

    Every report inherits from this class.

    Responsibilities

    • PDF document creation
    • Header
    • Footer
    • Common layout
    • Story management
    • Build PDF

    =========================================================
    """

    def __init__(self, report_title):

        self.report_title = report_title

        self.buffer = BytesIO()

        self.document = SimpleDocTemplate(

            self.buffer,

            pagesize=A4,

            leftMargin=PAGE_MARGIN,

            rightMargin=PAGE_MARGIN,

            topMargin=PAGE_MARGIN,

            bottomMargin=PAGE_MARGIN,

            title=report_title,

            author=PLATFORM_NAME,

        )

        self.story = []

    # =====================================================
    # BASIC COMPONENTS
    # =====================================================

    def add_header(self):

        self.story.extend(

            report_header(

                self.report_title

            )

        )

    def add_footer(self):

        self.story.extend(

            report_footer()

        )

    def add(self, component):

        self.story.append(component)

    def add_many(self, components):

        self.story.extend(components)

    def space(self, value=0.20):

        self.story.append(

            gap(value)

        )

    # =====================================================
    # BUILD
    # =====================================================

    def build(self):

        self.document.build(

            self.story,

            onFirstPage=self.draw_footer,

            onLaterPages=self.draw_footer,

        )

        pdf = self.buffer.getvalue()

        self.buffer.close()

        return pdf

    # =====================================================
    # PAGE FOOTER
    # =====================================================

    @staticmethod
    def draw_footer(canvas, document):

        canvas.saveState()

        canvas.setFont(

            "Helvetica",

            8,

        )

        page = canvas.getPageNumber()

        footer = (

            f"Generated by Textile Waste Intelligence Platform"

        )

        canvas.drawString(

            40,

            30,

            footer,

        )

        canvas.drawRightString(

            560,

            30,

            f"Page {page}",

        )

        canvas.restoreState()