from reportlab.platypus import (
    PageBreak,
)

from .base_report import BaseReport

from .helpers import (
    section,
    body,
)

from .constants import (
    COMPREHENSIVE_REPORT,
)

from .dashboard_report import DashboardReport
from .material_report import MaterialReport
from .waste_report import WasteReport
from .inventory_report import InventoryReport
from .sustainability_report import SustainabilityReport
from .collection_report import CollectionReport
from .waste_source_report import WasteSourceReport


class ComprehensiveReport(BaseReport):
    """
    ========================================================

        Textile Waste Intelligence Platform

            Comprehensive Report

    Complete enterprise sustainability report.

    ========================================================
    """

    def __init__(self, data):

        super().__init__(COMPREHENSIVE_REPORT)

        self.data = data

    # =====================================================

    def generate(self):

        self.cover_page()

        self.executive_summary()

        self.dashboard_section()

        self.company_section()

        self.collection_section()

        self.material_section()

        self.waste_section()

        self.inventory_section()

        self.sustainability_section()

        self.final_recommendation()

        return self.build()

    # =====================================================

    def cover_page(self):

        self.add_header()

        self.add(
            section(
                "Comprehensive Sustainability Report"
            )
        )

        self.add(
            body(
                "This document provides a complete "
                "overview of textile waste management, "
                "AI analysis, sustainability assessment, "
                "resource recovery and environmental "
                "performance generated by the Textile "
                "Waste Intelligence Platform."
            )
        )

        self.story.append(PageBreak())

    # =====================================================

    def executive_summary(self):

        self.add(section("Executive Summary"))

        self.add(
            body(
                self.data["executive_summary"]
            )
        )

        self.story.append(PageBreak())

    # =====================================================

    def dashboard_section(self):

        dashboard = DashboardReport(
            self.data["dashboard"]
        )

        dashboard.generate()

        self.story.extend(
            dashboard.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def company_section(self):

        report = WasteSourceReport(
            self.data["company"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def collection_section(self):

        report = CollectionReport(
            self.data["collection"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def material_section(self):

        report = MaterialReport(
            self.data["material"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def waste_section(self):

        report = WasteReport(
            self.data["waste"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def inventory_section(self):

        report = InventoryReport(
            self.data["inventory"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def sustainability_section(self):

        report = SustainabilityReport(
            self.data["sustainability"]
        )

        report.generate()

        self.story.extend(
            report.story
        )

        self.story.append(PageBreak())

    # =====================================================

    def final_recommendation(self):

        self.add(
            section(
                "Final Recommendations"
            )
        )

        self.add(
            body(
                self.data["recommendation"]
            )
        )

        self.add_footer()