from datetime import datetime

# ==========================================================
# PLATFORM
# ==========================================================

PLATFORM_NAME = "Textile Waste Intelligence Platform"

PLATFORM_SHORT_NAME = "TWIP"

VERSION = "1.0"

REPORT_VERSION = "1.0"

# ==========================================================
# ORGANIZATION
# ==========================================================

ORGANIZATION_NAME = "Infosys Springboard Virtual Internship"

PROJECT_NAME = "AI Powered Textile Waste Intelligence Platform"

AUTHOR = "TWIP AI Reporting Engine"

# ==========================================================
# REPORT TITLES
# ==========================================================

ANALYSIS_REPORT = "AI Analysis Report"

MATERIAL_REPORT = "Material Intelligence Report"

WASTE_REPORT = "Waste Classification Report"

INVENTORY_REPORT = "Inventory Report"

COLLECTION_REPORT = "Collection Report"

WASTE_SOURCE_REPORT = "Waste Source Report"

SUSTAINABILITY_REPORT = "Sustainability Report"

DASHBOARD_REPORT = "Executive Dashboard Report"

COMPREHENSIVE_REPORT = "Comprehensive Sustainability Report"

# ==========================================================
# FOOTER
# ==========================================================

FOOTER_TEXT = (
    "Generated by Textile Waste Intelligence Platform "
    "(TWIP)"
)

COPYRIGHT = (
    f"© {datetime.now().year} Textile Waste Intelligence Platform"
)

DISCLAIMER = (
    "This report is automatically generated using AI-based "
    "textile waste analysis and sustainability assessment. "
    "Values are estimated for decision support."
)

# ==========================================================
# UNITS
# ==========================================================

UNIT_WEIGHT = "kg"

UNIT_CARBON = "kg "

UNIT_WATER = "L"

UNIT_ENERGY = "kWh"

UNIT_PERCENT = "%"

# ==========================================================
# RATINGS
# ==========================================================

GRADE_EXCELLENT = "Excellent"

GRADE_GOOD = "Good"

GRADE_FAIR = "Fair"

GRADE_POOR = "Poor"

GRADE_CRITICAL = "Critical"

# ==========================================================
# REPORT STATUS
# ==========================================================

STATUS_COMPLETED = "Completed"

STATUS_PENDING = "Pending"

STATUS_FAILED = "Failed"

# ==========================================================
# DEFAULT VALUES
# ==========================================================

DEFAULT_TEXT = "Not Available"

DEFAULT_NUMBER = 0

DEFAULT_PERCENTAGE = 0.0

# ==========================================================
# FILE PREFIXES
# ==========================================================

PDF_PREFIX = "TWIP"

CSV_PREFIX = "TWIP"

EXCEL_PREFIX = "TWIP"

# ==========================================================
# DATE FORMAT
# ==========================================================

DATE_FORMAT = "%d %B %Y"

DATE_TIME_FORMAT = "%d %B %Y %I:%M %p"

# ==========================================================
# COMPANY COMPARISON
# ==========================================================

TOP_COMPANY = "Top Performing Organization"

BOTTOM_COMPANY = "Needs Sustainability Improvement"

# ==========================================================
# RECOMMENDATION LEVELS
# ==========================================================

LOW = "Low"

MEDIUM = "Medium"

HIGH = "High"

CRITICAL = "Critical"

# ==========================================================
# KPI LABELS
# ==========================================================

TOTAL_WASTE = "Total Textile Waste"

RECOVERED_WASTE = "Recovered Waste"

RECOVERY_RATE = "Recovery Rate"

CARBON_SAVED = "Carbon Saved"

WATER_SAVED = "Water Saved"

ENERGY_SAVED = "Energy Saved"

SUSTAINABILITY_SCORE = "Sustainability Score"

CIRCULARITY_SCORE = "Circular Economy Score"

RESOURCE_RECOVERY = "Resource Recovery"

LANDFILL_DIVERSION = "Landfill Diversion"

REUSE_SCORE = "Reuse Score"

MATERIAL_RECOVERY = "Material Recovery Score"