from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List
from uuid import UUID

from app.database.session import get_db
from app.models.user import User, Role, Organization
from app.models.support import ActivityLog
from app.schemas.user import UserResponse, UserUpdate, RoleResponse, UserCreate, UserAdminUpdate
from app.auth.deps import get_current_user, RoleChecker
from app.auth.security import get_password_hash

router = APIRouter(prefix="/users", tags=["Users"])

@router.get("/me", response_model=UserResponse)
def read_current_user(current_user: User = Depends(get_current_user)):
    return current_user

@router.put("/me", response_model=UserResponse)
def update_profile(
    user_in: UserUpdate,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    # Update text fields
    if user_in.full_name is not None:
        current_user.full_name = user_in.full_name
    if user_in.contact_details is not None:
        current_user.contact_details = user_in.contact_details
    if user_in.profile_picture is not None:
        current_user.profile_picture = user_in.profile_picture
        
    # Update organization name
    if user_in.organization_name is not None:
        if user_in.organization_name.strip() == "":
            current_user.organization_id = None
        else:
            org = db.query(Organization).filter(Organization.name == user_in.organization_name).first()
            if not org:
                # Auto-create organization if not found
                org = Organization(
                    name=user_in.organization_name,
                    type="Manufacturer" if "manufacturer" in current_user.role.name.lower() else "Recycler",
                    description=f"Auto-generated organization for {user_in.organization_name}",
                    contact_email=current_user.email
                )
                db.add(org)
                db.commit()
                db.refresh(org)
            current_user.organization_id = org.id

    # Update password if provided
    if user_in.password is not None and user_in.password.strip() != "":
        current_user.hashed_password = get_password_hash(user_in.password)

    db.add(current_user)
    
    # Audit log
    log = ActivityLog(
        user_id=current_user.id,
        action="UPDATE_PROFILE",
        details="User modified profile contact, organization, or credentials."
    )
    db.add(log)
    db.commit()
    db.refresh(current_user)
    
    return current_user

@router.get("/roles", response_model=List[RoleResponse])
def list_roles(db: Session = Depends(get_db)):
    return db.query(Role).all()

# Admin-only: list all users
@router.get("/", response_model=List[UserResponse])
def list_all_users(
    db: Session = Depends(get_db),
    admin_user: User = Depends(RoleChecker(["Administrator"]))
):
    return db.query(User).all()

# Admin-only: create new user
@router.post("/", response_model=UserResponse, status_code=status.HTTP_201_CREATED)
def admin_create_user(
    user_in: UserCreate,
    db: Session = Depends(get_db),
    admin_user: User = Depends(RoleChecker(["Administrator"]))
):
    # Check if user already exists
    existing = db.query(User).filter(User.email == user_in.email).first()
    if existing:
        raise HTTPException(status_code=400, detail="A user with this email address already exists.")
        
    # Get role
    role = db.query(Role).filter(Role.name == user_in.role_name).first()
    if not role:
        raise HTTPException(status_code=404, detail=f"Role '{user_in.role_name}' does not exist.")
        
    # Get or create organization
    org = None
    if user_in.organization_name and user_in.organization_name.strip() != "":
        org = db.query(Organization).filter(Organization.name == user_in.organization_name).first()
        if not org:
            org = Organization(
                name=user_in.organization_name,
                type="Manufacturer" if "manufacturer" in user_in.role_name.lower() else "Recycler",
                description=f"Auto-generated by Administrator creation",
                contact_email=user_in.email
            )
            db.add(org)
            db.commit()
            db.refresh(org)
            
    # Hash password
    hashed_pwd = get_password_hash(user_in.password)
    
    # Create user
    new_user = User(
        email=user_in.email,
        hashed_password=hashed_pwd,
        full_name=user_in.full_name,
        role_id=role.id,
        organization_id=org.id if org else None,
        is_active=True
    )
    db.add(new_user)
    db.commit()
    db.refresh(new_user)
    
    # Audit log
    log = ActivityLog(
        user_id=admin_user.id,
        action="ADMIN_CREATE_USER",
        details=f"Admin created user {new_user.email} (Role: {role.name})"
    )
    db.add(log)
    db.commit()
    
    return new_user

# Admin-only: update user details
@router.put("/{user_id}", response_model=UserResponse)
def admin_update_user(
    user_id: UUID,
    user_in: UserAdminUpdate,
    db: Session = Depends(get_db),
    admin_user: User = Depends(RoleChecker(["Administrator"]))
):
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    # Update email
    if user_in.email is not None:
        taken = db.query(User).filter(User.email == user_in.email, User.id != user_id).first()
        if taken:
            raise HTTPException(status_code=400, detail="This email is already in use.")
        user.email = user_in.email
        
    # Update full name
    if user_in.full_name is not None:
        user.full_name = user_in.full_name
        
    # Update active status
    if user_in.is_active is not None:
        user.is_active = user_in.is_active
        
    # Update role
    if user_in.role_name is not None:
        role = db.query(Role).filter(Role.name == user_in.role_name).first()
        if not role:
            raise HTTPException(status_code=404, detail=f"Role '{user_in.role_name}' does not exist.")
        user.role_id = role.id
        
    # Update organization
    if user_in.organization_name is not None:
        if user_in.organization_name.strip() == "":
            user.organization_id = None
        else:
            org = db.query(Organization).filter(Organization.name == user_in.organization_name).first()
            if not org:
                org = Organization(
                    name=user_in.organization_name,
                    type="Manufacturer" if "manufacturer" in (user_in.role_name or user.role.name).lower() else "Recycler",
                    description=f"Auto-generated by Admin user update",
                    contact_email=user_in.email or user.email
                )
                db.add(org)
                db.commit()
                db.refresh(org)
            user.organization_id = org.id
            
    # Update password
    if user_in.password is not None and user_in.password.strip() != "":
        user.hashed_password = get_password_hash(user_in.password)
        
    db.add(user)
    
    # Audit log
    log = ActivityLog(
        user_id=admin_user.id,
        action="ADMIN_UPDATE_USER",
        details=f"Admin modified user account settings for {user.email}"
    )
    db.add(log)
    db.commit()
    db.refresh(user)
    
    return user

# Admin-only: delete user
@router.delete("/{user_id}", status_code=status.HTTP_200_OK)
def admin_delete_user(
    user_id: UUID,
    db: Session = Depends(get_db),
    admin_user: User = Depends(RoleChecker(["Administrator"]))
):
    if user_id == admin_user.id:
        raise HTTPException(status_code=400, detail="Cannot self-terminate active administration accounts.")
        
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
        
    email = user.email
    db.delete(user)
    
    # Audit log
    log = ActivityLog(
        user_id=admin_user.id,
        action="ADMIN_DELETE_USER",
        details=f"Admin terminated user account {email}"
    )
    db.add(log)
    db.commit()
    
    return {"detail": f"User {email} has been deleted successfully."}
