from sqlalchemy import select

from app.database import SessionLocal
from app.models import Role


SYSTEM_ROLES = [
    {
        "name": "ADMIN",
        "description": "Full platform administration and system management.",
    },
    {
        "name": "OPERATOR",
        "description": "Handles textile waste registration and operational processing.",
    },
    {
        "name": "SUSTAINABILITY_MANAGER",
        "description": "Monitors sustainability performance, analytics, and reports.",
    },
    {
        "name": "MANUFACTURER",
        "description": "Registers and monitors textile waste generated by the organization.",
    },
]


def seed_roles() -> None:
    db = SessionLocal()

    try:
        for role_data in SYSTEM_ROLES:
            existing_role = db.scalar(
                select(Role).where(Role.name == role_data["name"])
            )

            if existing_role is None:
                db.add(Role(**role_data))
                print(f"Created role: {role_data['name']}")
            else:
                print(f"Role already exists: {role_data['name']}")

        db.commit()
        print("\nRole seeding completed successfully.")

    except Exception:
        db.rollback()
        raise

    finally:
        db.close()


if __name__ == "__main__":
    seed_roles()