import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Cell,
} from "recharts";

import { Card } from "../ui";
import useDashboard from "../../hooks/useDashboard";

const COLORS = [
  "#10B981",
  "#2563EB",
  "#F59E0B",
  "#EF4444",
  "#8B5CF6",
  "#06B6D4",
];

function WasteCategoryChart() {

  const {

    wasteDistribution,

    isLoading,

  } = useDashboard();

  if (isLoading) {

    return (

      <Card
        title="Waste Category Distribution"
        subtitle="Loading..."
      >

        <div className="h-80 animate-pulse rounded-2xl bg-slate-100" />

      </Card>

    );

  }

  const chartData =
    wasteDistribution?.map((item) => ({

      category:
        item.category ??
        item.waste_category ??
        "Unknown",

      value:
        item.count ??
        item.total ??
        0,

    })) ?? [];

  const total = chartData.reduce(

    (sum, item) =>

      sum + item.value,

    0

  );

  return (

    <Card
      title="Waste Category Distribution"
      subtitle="Classification of textile waste generated by AI."
    >

      {chartData.length === 0 ? (

        <div className="flex h-80 items-center justify-center text-muted">

          No waste data available.

        </div>

      ) : (

        <>

          <div className="h-80">

            <ResponsiveContainer
              width="100%"
              height="100%"
            >

              <BarChart data={chartData}>

                <CartesianGrid
                  strokeDasharray="3 3"
                  vertical={false}
                />

                <XAxis
                  dataKey="category"
                />

                <YAxis />

                <Tooltip
                  formatter={(value) => [
                    value,
                    "Records",
                  ]}
                />

                <Bar
                  dataKey="value"
                  radius={[8, 8, 0, 0]}
                >

                  {chartData.map(
                    (_, index) => (

                      <Cell

                        key={index}

                        fill={
                          COLORS[
                            index %
                            COLORS.length
                          ]
                        }

                      />

                    )
                  )}

                </Bar>

              </BarChart>

            </ResponsiveContainer>

          </div>

          <div className="mt-8 space-y-4">

            {chartData.map(
              (item, index) => (

                <div

                  key={item.category}

                  className="flex items-center justify-between rounded-xl border border-slate-200 p-4"

                >

                  <div className="flex items-center gap-3">

                    <span

                      className="h-3 w-3 rounded-full"

                      style={{
                        background:
                          COLORS[
                            index %
                            COLORS.length
                          ],
                      }}

                    />

                    <div>

                      <h4 className="font-semibold">

                        {item.category}

                      </h4>

                      <p className="text-xs text-muted">

                        {total
                          ? (
                              item.value /
                              total *
                              100
                            ).toFixed(1)
                          : 0}
                        %

                      </p>

                    </div>

                  </div>

                  <span className="text-lg font-bold text-green-600">

                    {item.value}

                  </span>

                </div>

              )
            )}

          </div>

        </>

      )}

    </Card>

  );

}

export default WasteCategoryChart;