import {
  Brain,
  BadgeCheck,
  Factory,
  Layers,
  Leaf,
  Recycle,
  ShieldCheck,
  Sparkles,
  Calendar,
  FileText,
  CheckCircle2,
  Circle,
} from "lucide-react";

import { Card, MetricCard } from "../ui";

/* -------------------------------------------------------
                    Utility Functions
------------------------------------------------------- */

function value(value, suffix = "") {
  if (
    value === null ||
    value === undefined ||
    value === ""
  ) {
    return "Not Available";
  }

  return `${value}${suffix}`;
}

function booleanValue(v) {
  return v ? "Yes" : "No";
}

/* -------------------------------------------------------
                Reusable Score Card
------------------------------------------------------- */

function ScoreCard({
  title,
  value: score,
  color,
}) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5">

      <div className="flex items-center justify-between">

        <h3 className="font-semibold text-heading">
          {title}
        </h3>

        <span
          className={`rounded-full px-3 py-1 text-sm font-semibold ${color}`}
        >
          {score}/100
        </span>

      </div>

      <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-200">

        <div
          className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 transition-all duration-700"
          style={{
            width: `${score}%`,
          }}
        />

      </div>

    </div>
  );
}

/* -------------------------------------------------------
                    Component
------------------------------------------------------- */

function AnalysisResult({ result }) {

  if (!result) return null;

  return (

    <div className="space-y-8">

      {/* =======================================================
                    Executive Summary
      ======================================================= */}

      <Card
        title="AI Textile Analysis Report"
        subtitle="Executive summary generated by the Textile Waste Intelligence Platform."
      >

        <div className="space-y-8">

          <div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">

            <div>

              <div className="flex items-center gap-4">

                <div className="rounded-2xl bg-blue-100 p-4">

                  <Brain
                    size={32}
                    className="text-blue-600"
                  />

                </div>

                <div>

                  <h2 className="text-3xl font-bold text-heading">

                    {result.material}

                  </h2>

                  <p className="text-muted">

                    AI Material Classification

                  </p>

                </div>

              </div>

            </div>

            <div className="rounded-2xl border bg-slate-50 px-6 py-4">

              <div className="flex items-center gap-2">

                <Calendar size={18} />

                {new Date(
                  result.created_at
                ).toLocaleString()}

              </div>

            </div>

          </div>

          <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

            <MetricCard
              icon={Brain}
              title="Confidence"
              value={value(
                result.confidence,
                "%"
              )}
              color="bg-blue-100 text-blue-700"
            />

            <MetricCard
              icon={Recycle}
              title="Waste Category"
              value={result.waste_category}
              color="bg-green-100 text-green-700"
            />

            <MetricCard
              icon={Leaf}
              title="Overall Score"
              value={value(
                result.overall_score,
                "/100"
              )}
              color="bg-emerald-100 text-emerald-700"
            />

            <MetricCard
              icon={ShieldCheck}
              title="ESG Score"
              value={value(
                result.esg_score,
                "/100"
              )}
              color="bg-violet-100 text-violet-700"
            />

          </div>

          <div className="rounded-2xl border border-green-200 bg-green-50 p-6">

            <div className="flex gap-4">

              <CheckCircle2
                size={28}
                className="text-green-600"
              />

              <div>

                <h3 className="text-xl font-semibold text-green-800">

                  Analysis Completed Successfully

                </h3>

                <p className="mt-3 leading-7 text-green-700">

                  The uploaded textile image has been analyzed
                  successfully. Material classification,
                  sustainability assessment, environmental
                  metrics and recommendation engine outputs
                  have been generated.

                </p>

              </div>

            </div>

          </div>

        </div>

      </Card>

      {/* =======================================================
                    Material Intelligence
      ======================================================= */}

      <Card
        title="Material Intelligence"
        subtitle="AI identified textile characteristics."
      >

        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

          <MetricCard
            icon={Factory}
            title="Material"
            value={result.material}
            color="bg-blue-100 text-blue-700"
          />

          <MetricCard
            icon={Layers}
            title="Category"
            value={result.material_category}
            color="bg-cyan-100 text-cyan-700"
          />

          <MetricCard
            icon={Sparkles}
            title="Quality"
            value={result.material_quality}
            color="bg-purple-100 text-purple-700"
          />

          <MetricCard
            icon={Recycle}
            title="Recycled Content"
            value={value(
              result.recycled_content,
              "%"
            )}
            color="bg-green-100 text-green-700"
          />

          <MetricCard
            icon={BadgeCheck}
            title="Biodegradable"
            value={booleanValue(
              result.biodegradable
            )}
            color="bg-lime-100 text-lime-700"
          />

          <MetricCard
            icon={BadgeCheck}
            title="Recyclable"
            value={booleanValue(
              result.recyclable
            )}
            color="bg-emerald-100 text-emerald-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Material Composition
      ======================================================= */}

      <Card
        title="Material Composition"
        subtitle="Fiber composition predicted by AI."
      >

        <div className="grid gap-5 md:grid-cols-3">

          <MetricCard
            icon={Circle}
            title="Primary Material"
            value={result.primary_material}
            color="bg-blue-100 text-blue-700"
          />

          <MetricCard
            icon={Circle}
            title="Secondary Material"
            value={
              result.secondary_material ||
              "Not Available"
            }
            color="bg-cyan-100 text-cyan-700"
          />

          <MetricCard
            icon={Layers}
            title="Composition"
            value={
              result.composition ||
              "Not Available"
            }
            color="bg-emerald-100 text-emerald-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Waste Intelligence
      ======================================================= */}

      <Card
        title="Waste Intelligence"
        subtitle="AI-generated waste classification and recycling pathway."
      >

        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

          <MetricCard
            icon={Recycle}
            title="Waste Category"
            value={result.waste_category}
            color="bg-blue-100 text-blue-700"
          />

          <MetricCard
            icon={Recycle}
            title="Waste Subcategory"
            value={result.waste_subcategory}
            color="bg-cyan-100 text-cyan-700"
          />

          <MetricCard
            icon={Leaf}
            title="Reuse Potential"
            value={result.reuse_potential}
            color="bg-green-100 text-green-700"
          />

          <MetricCard
            icon={Factory}
            title="Recycling Method"
            value={result.recycling_method}
            color="bg-violet-100 text-violet-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Circular Economy Scores
      ======================================================= */}

      <Card
        title="Circular Economy Assessment"
        subtitle="AI-generated sustainability and recovery scores."
      >

        <div className="grid gap-6 lg:grid-cols-2">

          <ScoreCard
            title="Recyclability Score"
            value={result.recyclability_score}
            color="bg-green-100 text-green-700"
          />

          <ScoreCard
            title="Reuse Score"
            value={result.reuse_score}
            color="bg-blue-100 text-blue-700"
          />

          <ScoreCard
            title="Material Recovery Score"
            value={result.material_recovery_score}
            color="bg-cyan-100 text-cyan-700"
          />

          <ScoreCard
            title="Circularity Score"
            value={result.circularity_score}
            color="bg-purple-100 text-purple-700"
          />

          <ScoreCard
            title="Sustainability Score"
            value={result.sustainability_score}
            color="bg-emerald-100 text-emerald-700"
          />

          <ScoreCard
            title="Environmental Score"
            value={result.environmental_score}
            color="bg-lime-100 text-lime-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Environmental Assessment
      ======================================================= */}

      <Card
        title="Environmental Assessment"
        subtitle="Estimated environmental impact generated by AI."
      >

        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

          <MetricCard
            icon={Leaf}
            title="Carbon Footprint"
            value={`${result.carbon_footprint} kg CO2`}
            color="bg-red-100 text-red-700"
          />

          <MetricCard
            icon={Leaf}
            title="Carbon Savings"
            value={`${result.carbon_savings} kg CO2`}
            color="bg-green-100 text-green-700"
          />

          <MetricCard
            icon={Leaf}
            title="Water Consumption"
            value={`${result.water_consumption} L`}
            color="bg-blue-100 text-blue-700"
          />

          <MetricCard
            icon={Leaf}
            title="Water Savings"
            value={`${result.water_savings} L`}
            color="bg-cyan-100 text-cyan-700"
          />

          <MetricCard
            icon={Factory}
            title="Energy Consumption"
            value={`${result.energy_consumption} kWh`}
            color="bg-orange-100 text-orange-700"
          />

          <MetricCard
            icon={Factory}
            title="Energy Savings"
            value={`${result.energy_savings} kWh`}
            color="bg-emerald-100 text-emerald-700"
          />

          <MetricCard
            icon={Recycle}
            title="Landfill Diversion"
            value={`${result.landfill_diversion}%`}
            color="bg-violet-100 text-violet-700"
          />

          <MetricCard
            icon={ShieldCheck}
            title="Resource Conservation"
            value={`${result.resource_conservation}%`}
            color="bg-lime-100 text-lime-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Overall AI Performance
      ======================================================= */}

      <Card
        title="Overall AI Performance"
        subtitle="Final evaluation generated from all AI engines."
      >

        <div className="grid gap-6 md:grid-cols-3">

          <div className="rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-600 p-8 text-white">

            <h3 className="text-lg font-semibold">

              Overall Score

            </h3>

            <p className="mt-5 text-6xl font-bold">

              {result.overall_score}

            </p>

            <p className="mt-3 text-blue-100">

              Combined AI assessment

            </p>

          </div>

          <div className="rounded-2xl bg-gradient-to-br from-green-600 to-emerald-600 p-8 text-white">

            <h3 className="text-lg font-semibold">

              Sustainability

            </h3>

            <p className="mt-5 text-6xl font-bold">

              {result.sustainability_score}

            </p>

            <p className="mt-3 text-green-100">

              Environmental sustainability

            </p>

          </div>

          <div className="rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-600 p-8 text-white">

            <h3 className="text-lg font-semibold">

              ESG

            </h3>

            <p className="mt-5 text-6xl font-bold">

              {result.esg_score}

            </p>

            <p className="mt-3 text-violet-100">

              ESG readiness score

            </p>

          </div>

        </div>

      </Card>

      {/* =======================================================
                    Sustainability Intelligence
      ======================================================= */}

      <Card
        title="Sustainability Intelligence"
        subtitle="Environmental, ESG and circular economy assessment."
      >

        <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">

          <MetricCard
            icon={Leaf}
            title="Sustainability Rating"
            value={result.sustainability_rating}
            color="bg-green-100 text-green-700"
          />

          <MetricCard
            icon={BadgeCheck}
            title="Status"
            value={result.sustainability_status}
            color="bg-emerald-100 text-emerald-700"
          />

          <MetricCard
            icon={ShieldCheck}
            title="Environmental Impact"
            value={result.environmental_impact}
            color="bg-cyan-100 text-cyan-700"
          />

          <MetricCard
            icon={Recycle}
            title="Circular Economy Index"
            value={`${result.circular_economy_index}/100`}
            color="bg-blue-100 text-blue-700"
          />

          <MetricCard
            icon={Factory}
            title="Recycling Target"
            value={`${result.recycling_target}%`}
            color="bg-violet-100 text-violet-700"
          />

          <MetricCard
            icon={CheckCircle2}
            title="Recycling Progress"
            value={`${result.recycling_progress}%`}
            color="bg-lime-100 text-lime-700"
          />

          <MetricCard
            icon={ShieldCheck}
            title="ESG Score"
            value={`${result.esg_score}/100`}
            color="bg-indigo-100 text-indigo-700"
          />

          <MetricCard
            icon={Sparkles}
            title="ESG Readiness"
            value={result.esg_readiness}
            color="bg-pink-100 text-pink-700"
          />

        </div>

      </Card>

      {/* =======================================================
                    Recommendation Engine
      ======================================================= */}

      <Card
        title="AI Recommendation Engine"
        subtitle="Recommended action plan generated by the AI engine."
      >

        <div className="grid gap-6 lg:grid-cols-2">

          <div className="space-y-5">

            <div className="rounded-2xl border border-red-200 bg-red-50 p-6">

              <h3 className="text-lg font-semibold text-red-700">

                Priority

              </h3>

              <p className="mt-3 text-3xl font-bold">

                {result.priority}

              </p>

            </div>

            <div className="rounded-2xl border border-blue-200 bg-blue-50 p-6">

              <h3 className="text-lg font-semibold text-blue-700">

                Recycling Recommendation

              </h3>

              <p className="mt-4 leading-8">

                {result.recommendation}

              </p>

            </div>

          </div>

          <div className="space-y-5">

            <div className="rounded-2xl border border-green-200 bg-green-50 p-6">

              <h3 className="text-lg font-semibold text-green-700">

                Next Step

              </h3>

              <p className="mt-4 leading-8">

                {result.next_step}

              </p>

            </div>

            <div className="rounded-2xl border border-violet-200 bg-violet-50 p-6">

              <h3 className="text-lg font-semibold text-violet-700">

                Expected Benefit

              </h3>

              <p className="mt-4 leading-8">

                {result.expected_benefit}

              </p>

            </div>

          </div>

        </div>

      </Card>

      {/* =======================================================
                    Report Summary
      ======================================================= */}

      <Card
        title="Analysis Summary"
        subtitle="Generated using the Textile Waste Intelligence Platform."
      >

        <div className="rounded-3xl bg-gradient-to-r from-blue-600 via-indigo-600 to-violet-600 p-8 text-white">

          <div className="flex items-center gap-4">

            <FileText size={34} />

            <div>

              <h2 className="text-2xl font-bold">

                AI Analysis Completed

              </h2>

              <p className="mt-2 text-blue-100">

                This report combines material recognition,
                waste classification, sustainability
                assessment, circular economy evaluation,
                environmental impact estimation and
                AI-powered recommendations into a single
                decision-support report.

              </p>

            </div>

          </div>

          <div className="mt-8 grid gap-6 md:grid-cols-4">

            <div>

              <p className="text-blue-100">

                Material

              </p>

              <h3 className="mt-2 text-xl font-bold">

                {result.material}

              </h3>

            </div>

            <div>

              <p className="text-blue-100">

                Confidence

              </p>

              <h3 className="mt-2 text-xl font-bold">

                {result.confidence}%

              </h3>

            </div>

            <div>

              <p className="text-blue-100">

                Overall Score

              </p>

              <h3 className="mt-2 text-xl font-bold">

                {result.overall_score}/100

              </h3>

            </div>

            <div>

              <p className="text-blue-100">

                Sustainability

              </p>

              <h3 className="mt-2 text-xl font-bold">

                {result.sustainability_rating}

              </h3>

            </div>

          </div>

        </div>

      </Card>

    </div>

  );

}

export default AnalysisResult;